// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALHybd3_h4RV7FF4hydKXlAk_uEJ_JftM',
    appId: '1:503791190135:web:2c1f675a618339de2b8672',
    messagingSenderId: '503791190135',
    projectId: 'flutterlogin-4a3f2',
    authDomain: 'flutterlogin-4a3f2.firebaseapp.com',
    databaseURL: 'https://flutterlogin-4a3f2-default-rtdb.firebaseio.com',
    storageBucket: 'flutterlogin-4a3f2.appspot.com',
    measurementId: 'G-W37XSHYW6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7aNVybcC9gHCmPrhHRJdXzdIQp6T-ZYk',
    appId: '1:503791190135:android:cd64401ce5764aee2b8672',
    messagingSenderId: '503791190135',
    projectId: 'flutterlogin-4a3f2',
    databaseURL: 'https://flutterlogin-4a3f2-default-rtdb.firebaseio.com',
    storageBucket: 'flutterlogin-4a3f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQBlrFn1lD4P_3Wri6GujDFjtTpAYxiWg',
    appId: '1:503791190135:ios:02c681080185bfd22b8672',
    messagingSenderId: '503791190135',
    projectId: 'flutterlogin-4a3f2',
    databaseURL: 'https://flutterlogin-4a3f2-default-rtdb.firebaseio.com',
    storageBucket: 'flutterlogin-4a3f2.appspot.com',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALHybd3_h4RV7FF4hydKXlAk_uEJ_JftM',
    appId: '1:503791190135:web:c0e51376599b52ef2b8672',
    messagingSenderId: '503791190135',
    projectId: 'flutterlogin-4a3f2',
    authDomain: 'flutterlogin-4a3f2.firebaseapp.com',
    databaseURL: 'https://flutterlogin-4a3f2-default-rtdb.firebaseio.com',
    storageBucket: 'flutterlogin-4a3f2.appspot.com',
    measurementId: 'G-86TLZTTRD6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQBlrFn1lD4P_3Wri6GujDFjtTpAYxiWg',
    appId: '1:503791190135:ios:02c681080185bfd22b8672',
    messagingSenderId: '503791190135',
    projectId: 'flutterlogin-4a3f2',
    databaseURL: 'https://flutterlogin-4a3f2-default-rtdb.firebaseio.com',
    storageBucket: 'flutterlogin-4a3f2.appspot.com',
    iosBundleId: 'com.example.flutterLogin',
  );

}